backend:
  name: git-gateway
  branch: main

site_url: https://www.uestcgal.top
display_url: https://www.uestcgal.top

locale: 'zh_Hans'
publish_mode: editorial_workflow

media_folder: 'src/assets/images'
public_folder: '~/assets/images'

collections:
  - name: 'post'
    label: '文章管理'
    folder: 'src/data/post'
    create: true
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '摘要', name: 'excerpt', widget: 'string' }
      - { label: '封面图', name: 'image', widget: 'image' }
      - { label: '发布日期', name: 'publishDate', widget: 'datetime' }
      - { label: '正文内容', name: 'body', widget: 'markdown' }
